# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module TeslaFleetManagementApi
  # A utility  that supports dateTime conversion to different formats
  class DateTimeHelper < CoreLibrary::DateTimeHelper
  end
end
