# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # EnergyController
  class EnergyController < BaseController
    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @param [BackupRequest] body Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def adjust_site_s_backup_reserve(energy_site_id,
                                     body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/energy_sites/{energy_site_id}/backup',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(BackupResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @param [Kind] kind Required parameter: Example:
    # @param [DateTime] start_date Required parameter: TODO: type description
    # here
    # @param [DateTime] end_date Required parameter: TODO: type description
    # here
    # @param [String] period Optional parameter: TODO: type description here
    # @param [String] time_zone Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_backup_or_energy_history(energy_site_id,
                                     kind,
                                     start_date,
                                     end_date,
                                     period: nil,
                                     time_zone: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/energy_sites/{energy_site_id}/calendar_history',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(kind, key: 'kind')
                                 .is_required(true))
                   .query_param(new_parameter(start_date, key: 'start_date')
                                 .is_required(true))
                   .query_param(new_parameter(end_date, key: 'end_date')
                                 .is_required(true))
                   .query_param(new_parameter(period, key: 'period'))
                   .query_param(new_parameter(time_zone, key: 'time_zone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CalendarHistoryResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @param [KindGetWallConnectorChargingHistory] kind Required parameter:
    # Example:
    # @param [DateTime] start_date Required parameter: TODO: type description
    # here
    # @param [DateTime] end_date Required parameter: TODO: type description
    # here
    # @param [String] time_zone Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_wall_connector_charging_history(energy_site_id,
                                            kind,
                                            start_date,
                                            end_date,
                                            time_zone: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/energy_sites/{energy_site_id}/telemetry_history',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(kind, key: 'kind')
                                 .is_required(true))
                   .query_param(new_parameter(start_date, key: 'start_date')
                                 .is_required(true))
                   .query_param(new_parameter(end_date, key: 'end_date')
                                 .is_required(true))
                   .query_param(new_parameter(time_zone, key: 'time_zone'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChargeHistoryResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_live_site_status(energy_site_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/energy_sites/{energy_site_id}/live_status',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(LiveStatusResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @param [OperationRequest] body Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def set_site_mode_autonomous_or_self_consumption(energy_site_id,
                                                     body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/energy_sites/{energy_site_id}/operation',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(GenericUpdateResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @param [Object] body Optional parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def allow_disallow_charging_from_the_grid_and_exporting_energy_to_the_grid(energy_site_id,
                                                                               body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/energy_sites/{energy_site_id}/grid_import_export',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(APIHelper.method(:json_serialize))
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(GenericUpdateResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @param [OffGridVehicleChargingReserveRequest] body Required parameter:
    # TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def adjust_site_s_off_grid_vehicle_charging_reserve(energy_site_id,
                                                        body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/energy_sites/{energy_site_id}/off_grid_vehicle_charging_reserve',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(GenericUpdateResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @param [StormModeRequest] body Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_storm_watch_participation(energy_site_id,
                                         body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/energy_sites/{energy_site_id}/storm_mode',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(GenericUpdateResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @param [TimeOfUseSettingsRequest] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_time_of_use_tou_settings(energy_site_id,
                                        body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/energy_sites/{energy_site_id}/time_of_use_settings',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(GenericUpdateResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_user_products_vehicles_energy_sites
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/products',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ProductsResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] energy_site_id Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_site_information_assets_settings_features(energy_site_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/energy_sites/{energy_site_id}/site_info',
                                     Server::DEFAULT)
                   .template_param(new_parameter(energy_site_id, key: 'energy_site_id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SiteInfoResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end
  end
end
