# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # VehiclesController
  class VehiclesController < BaseController
    # TODO: type endpoint description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_vehicles
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Api1VehiclesResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_vehicle(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles/{vehicle_tag}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Api1VehiclesResponseGetVehicle.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def mobile_enabled(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles/{vehicle_tag}/mobile_enabled',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Api1VehiclesMobileEnabledResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def nearby_charging_sites(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles/{vehicle_tag}/nearby_charging_sites',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Api1VehiclesNearbyChargingSitesResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def vehicle_live_data(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles/{vehicle_tag}/vehicle_data',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SiteInfoResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def wake_up_vehicle(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/wake_up',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Api1VehiclesWakeUpResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vin Required parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def vehicle_specs(vin)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles/{vin}/specs',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vin, key: 'vin')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SiteInfoResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vin Required parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def vehicle_options(vin)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/dx/vehicles/options',
                                     Server::DEFAULT)
                   .query_param(new_parameter(vin, key: 'vin')
                                 .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Api1DxVehiclesOptionsResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def warranty_details
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/dx/warranty/details',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Api1DxWarrantyDetailsResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_allowed_drivers_for_a_vehicle(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles/{vehicle_tag}/drivers',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DriversResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def remove_driver_access_from_a_vehicle(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/api/1/vehicles/{vehicle_tag}/drivers',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SimpleOkResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vin Required parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_eligible_vehicle_subscriptions(vin)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/dx/vehicles/subscriptions/eligibility',
                                     Server::DEFAULT)
                   .query_param(new_parameter(vin, key: 'vin')
                                 .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SiteInfoResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vin Required parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_eligible_vehicle_upgrades(vin)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/dx/vehicles/upgrades/eligibility',
                                     Server::DEFAULT)
                   .query_param(new_parameter(vin, key: 'vin')
                                 .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SiteInfoResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vin Required parameter: TODO: type description here
    # @param [EnterprisePayerRequest] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def set_enterprise_payer_roles(vin,
                                   body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/dx/enterprise/v1/{vin}/payer',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vin, key: 'vin')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vin Required parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_enterprise_roles_for_a_vehicle(vin)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/dx/enterprise/v1/{vin}/roles',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vin, key: 'vin')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:json_deserialize))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [FleetStatusRequest] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_fleet_status_for_vehicles(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/fleet_status',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:json_deserialize))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [Object] body Required parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_or_update_fleet_telemetry_configuration(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/fleet_telemetry_config',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(APIHelper.method(:json_serialize))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:json_deserialize))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_fleet_telemetry_configuration(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles/{vehicle_tag}/fleet_telemetry_config',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:json_deserialize))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_fleet_telemetry_configuration(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/api/1/vehicles/{vehicle_tag}/fleet_telemetry_config',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:json_deserialize))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [FleetTelemetryJwsRequest] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def configure_fleet_telemetry_using_signed_jws_token(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/fleet_telemetry_config_jws',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:json_deserialize))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_fleet_telemetry_errors_for_a_vehicle(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api/1/vehicles/{vehicle_tag}/fleet_telemetry_errors',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(And.new('bearerAuth', 'thirdpartytoken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:json_deserialize))
                    .is_api_response(true))
        .execute
    end
  end
end
