# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # VehicleCommandsController
  class VehicleCommandsController < BaseController
    # Controls the front or rear trunk
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @param [ActuateTrunkRequest] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def actuate_trunk(vehicle_tag,
                      body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/actuate_trunk',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @param [AddChargeScheduleRequest] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def add_charge_schedule(vehicle_tag,
                            body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/add_charge_schedule',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @param [AddPreconditionScheduleRequest] body Required parameter: TODO:
    # type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def add_precondition_schedule(vehicle_tag,
                                  body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/add_precondition_schedule',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @param [AdjustVolumeRequest] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def adjust_media_volume(vehicle_tag,
                            body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/adjust_volume',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def start_climate_preconditioning(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/auto_conditioning_start',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def stop_climate_preconditioning(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/auto_conditioning_stop',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cancel_software_update(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/cancel_software_update',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def charge_max_range(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/charge_max_range',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def open_charge_port_door(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/charge_port_door_open',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def close_charge_port_door(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/charge_port_door_close',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def charge_standard(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/charge_standard',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def start_charging(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/charge_start',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def stop_charging(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/charge_stop',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Deactivates PIN to Drive and resets the associated PIN for supported
    # firmware versions.
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def clear_pin_to_drive_admin(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/clear_pin_to_drive_admin',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def lock_doors(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/door_lock',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def unlock_doors(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/door_unlock',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Erases user data from the vehicle UI. Requires Guest Mode.
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def erase_user_data(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/erase_user_data',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Briefly flashes vehicle headlights.
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def flash_lights(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/flash_lights',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @param [GuestModeRequest] body Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def enable_or_disable_guest_mode(vehicle_tag,
                                     body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/guest_mode',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def honk_horn(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/honk_horn',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # TODO: type endpoint description here
    # @param [String] vehicle_tag Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def next_favorite_media_track(vehicle_tag)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/api/1/vehicles/{vehicle_tag}/command/media_next_fav',
                                     Server::DEFAULT)
                   .template_param(new_parameter(vehicle_tag, key: 'vehicle_tag')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('thirdpartytoken', 'bearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(CommandResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end
  end
end
