# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
