# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  #  tesla_fleet_management_api client class.
  class Client
    include CoreLibrary
    attr_reader :config, :auth_managers

    def user_agent_detail
      config.user_agent_detail
    end

    # Returns the configured authentication oauth2 instance.
    def oauth_2
      @auth_managers['oauth2']
    end

    # Access to charging controller.
    # @return [ChargingController] Returns the controller instance.
    def charging
      @charging ||= ChargingController.new @global_configuration
    end

    # Access to energy controller.
    # @return [EnergyController] Returns the controller instance.
    def energy
      @energy ||= EnergyController.new @global_configuration
    end

    # Access to partner controller.
    # @return [PartnerController] Returns the controller instance.
    def partner
      @partner ||= PartnerController.new @global_configuration
    end

    # Access to user controller.
    # @return [UserController] Returns the controller instance.
    def user
      @user ||= UserController.new @global_configuration
    end

    # Access to vehicles controller.
    # @return [VehiclesController] Returns the controller instance.
    def vehicles
      @vehicles ||= VehiclesController.new @global_configuration
    end

    # Access to oauth_authorization controller.
    # @return [OauthAuthorizationController] Returns the controller instance.
    def oauth_authorization
      @oauth_authorization ||= OauthAuthorizationController.new @global_configuration
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 60,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put], http_callback: nil, proxy_settings: nil,
      logging_configuration: nil, environment: Environment::PRODUCTION,
      bearer_auth_credentials: nil, oauth_2_credentials: nil, config: nil
    )
      @config = if config.nil?
                  Configuration.new(
                    connection: connection, adapter: adapter, timeout: timeout,
                    max_retries: max_retries, retry_interval: retry_interval,
                    backoff_factor: backoff_factor,
                    retry_statuses: retry_statuses,
                    retry_methods: retry_methods, http_callback: http_callback,
                    proxy_settings: proxy_settings,
                    logging_configuration: logging_configuration,
                    environment: environment,
                    bearer_auth_credentials: bearer_auth_credentials,
                    oauth_2_credentials: oauth_2_credentials
                  )
                else
                  config
                end
      user_agent_params = BaseController.user_agent_parameters

      @global_configuration = GlobalConfiguration.new(client_configuration: @config)
                                                 .base_uri_executor(@config.method(:get_base_uri))
                                                 .global_errors(BaseController::GLOBAL_ERRORS)
                                                 .user_agent(BaseController.user_agent,
                                                             agent_parameters: user_agent_params)

      initialize_auth_managers(@global_configuration)
      @global_configuration = @global_configuration.auth_managers(@auth_managers)
    end

    # Initializes the auth managers hash used for authenticating API calls.
    # @param [GlobalConfiguration] global_config The global configuration of the SDK)
    def initialize_auth_managers(global_config)
      @auth_managers = {}
      http_client_config = global_config.client_configuration
      %w[bearerAuth oauth2].each { |auth| @auth_managers[auth] = nil }
      @auth_managers['bearerAuth'] = BearerAuth.new(http_client_config.bearer_auth_credentials)
      @auth_managers['oauth2'] = Oauth2.new(http_client_config.oauth_2_credentials, global_config)
    end

    # Creates a client directly from environment variables.
    def self.from_env(**overrides)
      default_config = Configuration.build_default_config_from_env
      new_config = default_config.clone_with(**overrides)
      new(config: new_config)
    end
  end
end
