# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
require 'json'

require 'apimatic_core_interfaces'
require 'apimatic_core'
require 'apimatic_faraday_client_adapter'

require_relative 'tesla_fleet_management_api/api_helper'
require_relative 'tesla_fleet_management_api/client'

# Utilities
require_relative 'tesla_fleet_management_api/utilities/file_wrapper'
require_relative 'tesla_fleet_management_api/utilities/date_time_helper'

# Http
require_relative 'tesla_fleet_management_api/http/api_response'
require_relative 'tesla_fleet_management_api/http/http_call_back'
require_relative 'tesla_fleet_management_api/http/http_method_enum'
require_relative 'tesla_fleet_management_api/http/http_request'
require_relative 'tesla_fleet_management_api/http/http_response'
require_relative 'tesla_fleet_management_api/http/proxy_settings'


# Logger
require_relative 'tesla_fleet_management_api/logging/configuration/' \
                 'api_logging_configuration'
require_relative 'tesla_fleet_management_api/logging/sdk_logger'
require_relative 'tesla_fleet_management_api/http/auth/bearer_auth'
require_relative 'tesla_fleet_management_api/http/auth/thirdpartytoken'

# Models
require_relative 'tesla_fleet_management_api/models/base_model'
require_relative 'tesla_fleet_management_api/models/charging_history_response'
require_relative 'tesla_fleet_management_api/models/charging_history_data'
require_relative 'tesla_fleet_management_api/models/charging_history_item'
require_relative 'tesla_fleet_management_api/models/charging_fee'
require_relative 'tesla_fleet_management_api/models/charging_invoice'
require_relative 'tesla_fleet_management_api/models/charging_sessions_response'
require_relative 'tesla_fleet_management_api/models/charging_sessions_data'
require_relative 'tesla_fleet_management_api/models/charging_session'
require_relative 'tesla_fleet_management_api/models/charging_period'
require_relative 'tesla_fleet_management_api/models/charging_dimension'
require_relative 'tesla_fleet_management_api/models/tariffs'
require_relative 'tesla_fleet_management_api/models/tariff_element'
require_relative 'tesla_fleet_management_api/models/price_component'
require_relative 'tesla_fleet_management_api/models/total_cost'
require_relative 'tesla_fleet_management_api/models/location'
require_relative 'tesla_fleet_management_api/models/backup_request'
require_relative 'tesla_fleet_management_api/models/backup_response'
require_relative 'tesla_fleet_management_api/models/calendar_history_response'
require_relative 'tesla_fleet_management_api/models/charge_history_response'
require_relative 'tesla_fleet_management_api/models/live_status_response'
require_relative 'tesla_fleet_management_api/models/operation_request'
require_relative 'tesla_fleet_management_api/models/generic_update_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'off_grid_vehicle_charging_reserve_request'
require_relative 'tesla_fleet_management_api/models/storm_mode_request'
require_relative 'tesla_fleet_management_api/models/' \
                 'time_of_use_settings_request'
require_relative 'tesla_fleet_management_api/models/products_response'
require_relative 'tesla_fleet_management_api/models/site_info_response'
require_relative 'tesla_fleet_management_api/models/charge_duration'
require_relative 'tesla_fleet_management_api/models/charge_history'
require_relative 'tesla_fleet_management_api/models/charge_start_time'
require_relative 'tesla_fleet_management_api/models/event'
require_relative 'tesla_fleet_management_api/models/response'
require_relative 'tesla_fleet_management_api/models/tou_settings'
require_relative 'tesla_fleet_management_api/models/' \
                 'response_calendar_history_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'response_charge_history_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'response_live_status_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'fleet_telemetry_errors_response'
require_relative 'tesla_fleet_management_api/models/public_key_response'
require_relative 'tesla_fleet_management_api/models/register_partner_request'
require_relative 'tesla_fleet_management_api/models/register_partner_response'
require_relative 'tesla_fleet_management_api/models/fleet_telemetry_error'
require_relative 'tesla_fleet_management_api/models/response1'
require_relative 'tesla_fleet_management_api/models/' \
                 'response_fleet_telemetry_errors_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'response_public_key_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'response_register_partner_response'
require_relative 'tesla_fleet_management_api/models/me_response'
require_relative 'tesla_fleet_management_api/models/orders_response'
require_relative 'tesla_fleet_management_api/models/region_response'
require_relative 'tesla_fleet_management_api/models/response2'
require_relative 'tesla_fleet_management_api/models/signaling'
require_relative 'tesla_fleet_management_api/models/response_me_response'
require_relative 'tesla_fleet_management_api/models/response_orders_response'
require_relative 'tesla_fleet_management_api/models/response_region_response'
require_relative 'tesla_fleet_management_api/models/pagination'
require_relative 'tesla_fleet_management_api/models/vehicle_base'
require_relative 'tesla_fleet_management_api/models/mobile_enabled'
require_relative 'tesla_fleet_management_api/models/charging_location'
require_relative 'tesla_fleet_management_api/models/vehicle_option'
require_relative 'tesla_fleet_management_api/models/warranty_item'
require_relative 'tesla_fleet_management_api/models/simple_ok_response'
require_relative 'tesla_fleet_management_api/models/drivers_response'
require_relative 'tesla_fleet_management_api/models/driver'
require_relative 'tesla_fleet_management_api/models/enterprise_payer_request'
require_relative 'tesla_fleet_management_api/models/fleet_status_request'
require_relative 'tesla_fleet_management_api/models/fleet_telemetry_jws_request'
require_relative 'tesla_fleet_management_api/models/' \
                 'api1_dx_vehicles_options_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'api1_dx_warranty_details_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'api1_vehicles_mobile_enabled_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'api1_vehicles_nearby_charging_sites_response'
require_relative 'tesla_fleet_management_api/models/api1_vehicles_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'api1_vehicles_wake_up_response'
require_relative 'tesla_fleet_management_api/models/location1'
require_relative 'tesla_fleet_management_api/models/response3'
require_relative 'tesla_fleet_management_api/models/' \
                 'api1_vehicles_response_get_vehicle'
require_relative 'tesla_fleet_management_api/models/' \
                 'response_api1_dx_vehicles_options_response'
require_relative 'tesla_fleet_management_api/models/' \
                 'response_api1_dx_warranty_details_response'
require_relative 'tesla_fleet_management_api/models/command_result'
require_relative 'tesla_fleet_management_api/models/guest_mode_request'
require_relative 'tesla_fleet_management_api/models/actuate_trunk_request'
require_relative 'tesla_fleet_management_api/models/add_charge_schedule_request'
require_relative 'tesla_fleet_management_api/models/' \
                 'add_precondition_schedule_request'
require_relative 'tesla_fleet_management_api/models/adjust_volume_request'
require_relative 'tesla_fleet_management_api/models/command_response'
require_relative 'tesla_fleet_management_api/models/o_auth_token'
require_relative 'tesla_fleet_management_api/models/default_real_mode'
require_relative 'tesla_fleet_management_api/models/kind'
require_relative 'tesla_fleet_management_api/models/' \
                 'kind_get_wall_connector_charging_history'
require_relative 'tesla_fleet_management_api/models/which_trunk'
require_relative 'tesla_fleet_management_api/models/o_auth_provider_error'
require_relative 'tesla_fleet_management_api/models/' \
                 'o_auth_scope_thirdpartytoken'

# Exceptions
require_relative 'tesla_fleet_management_api/exceptions/api_exception'
require_relative 'tesla_fleet_management_api/exceptions/' \
                 'o_auth_provider_exception'

require_relative 'tesla_fleet_management_api/configuration'

# Controllers
require_relative 'tesla_fleet_management_api/controllers/base_controller'
require_relative 'tesla_fleet_management_api/controllers/charging_controller'
require_relative 'tesla_fleet_management_api/controllers/energy_controller'
require_relative 'tesla_fleet_management_api/controllers/partner_controller'
require_relative 'tesla_fleet_management_api/controllers/user_controller'
require_relative 'tesla_fleet_management_api/controllers/vehicles_controller'
require_relative 'tesla_fleet_management_api/controllers/' \
                 'vehicle_commands_controller'
require_relative 'tesla_fleet_management_api/controllers/' \
                 'o_auth_authorization_controller'
