# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # AddChargeScheduleRequest Model.
  class AddChargeScheduleRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :lat

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :lon

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :days_of_week

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :start_enabled

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :start_time

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :end_enabled

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :end_time

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :one_time

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :enabled

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['lat'] = 'lat'
      @_hash['lon'] = 'lon'
      @_hash['id'] = 'id'
      @_hash['days_of_week'] = 'days_of_week'
      @_hash['start_enabled'] = 'start_enabled'
      @_hash['start_time'] = 'start_time'
      @_hash['end_enabled'] = 'end_enabled'
      @_hash['end_time'] = 'end_time'
      @_hash['one_time'] = 'one_time'
      @_hash['enabled'] = 'enabled'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        days_of_week
        start_enabled
        start_time
        end_enabled
        end_time
        one_time
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(lat:, lon:, id:, enabled:, days_of_week: SKIP,
                   start_enabled: SKIP, start_time: SKIP, end_enabled: SKIP,
                   end_time: SKIP, one_time: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @lat = lat
      @lon = lon
      @id = id
      @days_of_week = days_of_week unless days_of_week == SKIP
      @start_enabled = start_enabled unless start_enabled == SKIP
      @start_time = start_time unless start_time == SKIP
      @end_enabled = end_enabled unless end_enabled == SKIP
      @end_time = end_time unless end_time == SKIP
      @one_time = one_time unless one_time == SKIP
      @enabled = enabled
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      lat = hash.key?('lat') ? hash['lat'] : nil
      lon = hash.key?('lon') ? hash['lon'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      enabled = hash.key?('enabled') ? hash['enabled'] : nil
      days_of_week = hash.key?('days_of_week') ? hash['days_of_week'] : SKIP
      start_enabled = hash.key?('start_enabled') ? hash['start_enabled'] : SKIP
      start_time = hash.key?('start_time') ? hash['start_time'] : SKIP
      end_enabled = hash.key?('end_enabled') ? hash['end_enabled'] : SKIP
      end_time = hash.key?('end_time') ? hash['end_time'] : SKIP
      one_time = hash.key?('one_time') ? hash['one_time'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      AddChargeScheduleRequest.new(lat: lat,
                                   lon: lon,
                                   id: id,
                                   enabled: enabled,
                                   days_of_week: days_of_week,
                                   start_enabled: start_enabled,
                                   start_time: start_time,
                                   end_enabled: end_enabled,
                                   end_time: end_time,
                                   one_time: one_time,
                                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} lat: #{@lat}, lon: #{@lon}, id: #{@id}, days_of_week: #{@days_of_week},"\
      " start_enabled: #{@start_enabled}, start_time: #{@start_time}, end_enabled:"\
      " #{@end_enabled}, end_time: #{@end_time}, one_time: #{@one_time}, enabled: #{@enabled},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} lat: #{@lat.inspect}, lon: #{@lon.inspect}, id: #{@id.inspect},"\
      " days_of_week: #{@days_of_week.inspect}, start_enabled: #{@start_enabled.inspect},"\
      " start_time: #{@start_time.inspect}, end_enabled: #{@end_enabled.inspect}, end_time:"\
      " #{@end_time.inspect}, one_time: #{@one_time.inspect}, enabled: #{@enabled.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
