# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ChargingSession Model.
  class ChargingSession < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :vin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :model

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :start_date_time

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :stop_date_time

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_energy

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_time

    # TODO: Write general description for this method
    # @return [TotalCost]
    attr_accessor :total_cost

    # TODO: Write general description for this method
    # @return [Location]
    attr_accessor :location

    # TODO: Write general description for this method
    # @return [Array[ChargingPeriod]]
    attr_accessor :charging_periods

    # TODO: Write general description for this method
    # @return [Tariffs]
    attr_accessor :tariffs

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['vin'] = 'vin'
      @_hash['model'] = 'model'
      @_hash['start_date_time'] = 'start_date_time'
      @_hash['stop_date_time'] = 'stop_date_time'
      @_hash['total_energy'] = 'total_energy'
      @_hash['total_time'] = 'total_time'
      @_hash['total_cost'] = 'total_cost'
      @_hash['location'] = 'location'
      @_hash['charging_periods'] = 'charging_periods'
      @_hash['tariffs'] = 'tariffs'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        vin
        model
        start_date_time
        stop_date_time
        total_energy
        total_time
        total_cost
        location
        charging_periods
        tariffs
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id: SKIP, vin: SKIP, model: SKIP, start_date_time: SKIP,
                   stop_date_time: SKIP, total_energy: SKIP, total_time: SKIP,
                   total_cost: SKIP, location: SKIP, charging_periods: SKIP,
                   tariffs: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @id = id unless id == SKIP
      @vin = vin unless vin == SKIP
      @model = model unless model == SKIP
      @start_date_time = start_date_time unless start_date_time == SKIP
      @stop_date_time = stop_date_time unless stop_date_time == SKIP
      @total_energy = total_energy unless total_energy == SKIP
      @total_time = total_time unless total_time == SKIP
      @total_cost = total_cost unless total_cost == SKIP
      @location = location unless location == SKIP
      @charging_periods = charging_periods unless charging_periods == SKIP
      @tariffs = tariffs unless tariffs == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      vin = hash.key?('vin') ? hash['vin'] : SKIP
      model = hash.key?('model') ? hash['model'] : SKIP
      start_date_time =
        hash.key?('start_date_time') ? hash['start_date_time'] : SKIP
      stop_date_time =
        hash.key?('stop_date_time') ? hash['stop_date_time'] : SKIP
      total_energy = hash.key?('total_energy') ? hash['total_energy'] : SKIP
      total_time = hash.key?('total_time') ? hash['total_time'] : SKIP
      total_cost = TotalCost.from_hash(hash['total_cost']) if hash['total_cost']
      location = Location.from_hash(hash['location']) if hash['location']
      # Parameter is an array, so we need to iterate through it
      charging_periods = nil
      unless hash['charging_periods'].nil?
        charging_periods = []
        hash['charging_periods'].each do |structure|
          charging_periods << (ChargingPeriod.from_hash(structure) if structure)
        end
      end

      charging_periods = SKIP unless hash.key?('charging_periods')
      tariffs = Tariffs.from_hash(hash['tariffs']) if hash['tariffs']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChargingSession.new(id: id,
                          vin: vin,
                          model: model,
                          start_date_time: start_date_time,
                          stop_date_time: stop_date_time,
                          total_energy: total_energy,
                          total_time: total_time,
                          total_cost: total_cost,
                          location: location,
                          charging_periods: charging_periods,
                          tariffs: tariffs,
                          additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, vin: #{@vin}, model: #{@model}, start_date_time:"\
      " #{@start_date_time}, stop_date_time: #{@stop_date_time}, total_energy: #{@total_energy},"\
      " total_time: #{@total_time}, total_cost: #{@total_cost}, location: #{@location},"\
      " charging_periods: #{@charging_periods}, tariffs: #{@tariffs}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, vin: #{@vin.inspect}, model: #{@model.inspect},"\
      " start_date_time: #{@start_date_time.inspect}, stop_date_time: #{@stop_date_time.inspect},"\
      " total_energy: #{@total_energy.inspect}, total_time: #{@total_time.inspect}, total_cost:"\
      " #{@total_cost.inspect}, location: #{@location.inspect}, charging_periods:"\
      " #{@charging_periods.inspect}, tariffs: #{@tariffs.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
