# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ChargingFee Model.
  class ChargingFee < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :session_fee_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :fee_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :currency_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :pricing_type

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :rate_base

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :rate_tier1

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :rate_tier2

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :rate_tier3

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :rate_tier4

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :usage_base

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :usage_tier1

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :usage_tier2

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :usage_tier3

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :usage_tier4

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_base

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_tier1

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_tier2

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_tier3

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_tier4

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_due

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :net_due

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :uom

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_paid

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['session_fee_id'] = 'sessionFeeId'
      @_hash['fee_type'] = 'feeType'
      @_hash['currency_code'] = 'currencyCode'
      @_hash['pricing_type'] = 'pricingType'
      @_hash['rate_base'] = 'rateBase'
      @_hash['rate_tier1'] = 'rateTier1'
      @_hash['rate_tier2'] = 'rateTier2'
      @_hash['rate_tier3'] = 'rateTier3'
      @_hash['rate_tier4'] = 'rateTier4'
      @_hash['usage_base'] = 'usageBase'
      @_hash['usage_tier1'] = 'usageTier1'
      @_hash['usage_tier2'] = 'usageTier2'
      @_hash['usage_tier3'] = 'usageTier3'
      @_hash['usage_tier4'] = 'usageTier4'
      @_hash['total_base'] = 'totalBase'
      @_hash['total_tier1'] = 'totalTier1'
      @_hash['total_tier2'] = 'totalTier2'
      @_hash['total_tier3'] = 'totalTier3'
      @_hash['total_tier4'] = 'totalTier4'
      @_hash['total_due'] = 'totalDue'
      @_hash['net_due'] = 'netDue'
      @_hash['uom'] = 'uom'
      @_hash['is_paid'] = 'isPaid'
      @_hash['status'] = 'status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        session_fee_id
        fee_type
        currency_code
        pricing_type
        rate_base
        rate_tier1
        rate_tier2
        rate_tier3
        rate_tier4
        usage_base
        usage_tier1
        usage_tier2
        usage_tier3
        usage_tier4
        total_base
        total_tier1
        total_tier2
        total_tier3
        total_tier4
        total_due
        net_due
        uom
        is_paid
        status
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        rate_tier3
        rate_tier4
        usage_tier3
        usage_tier4
      ]
    end

    def initialize(session_fee_id: SKIP, fee_type: SKIP, currency_code: SKIP,
                   pricing_type: SKIP, rate_base: SKIP, rate_tier1: SKIP,
                   rate_tier2: SKIP, rate_tier3: SKIP, rate_tier4: SKIP,
                   usage_base: SKIP, usage_tier1: SKIP, usage_tier2: SKIP,
                   usage_tier3: SKIP, usage_tier4: SKIP, total_base: SKIP,
                   total_tier1: SKIP, total_tier2: SKIP, total_tier3: SKIP,
                   total_tier4: SKIP, total_due: SKIP, net_due: SKIP, uom: SKIP,
                   is_paid: SKIP, status: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @session_fee_id = session_fee_id unless session_fee_id == SKIP
      @fee_type = fee_type unless fee_type == SKIP
      @currency_code = currency_code unless currency_code == SKIP
      @pricing_type = pricing_type unless pricing_type == SKIP
      @rate_base = rate_base unless rate_base == SKIP
      @rate_tier1 = rate_tier1 unless rate_tier1 == SKIP
      @rate_tier2 = rate_tier2 unless rate_tier2 == SKIP
      @rate_tier3 = rate_tier3 unless rate_tier3 == SKIP
      @rate_tier4 = rate_tier4 unless rate_tier4 == SKIP
      @usage_base = usage_base unless usage_base == SKIP
      @usage_tier1 = usage_tier1 unless usage_tier1 == SKIP
      @usage_tier2 = usage_tier2 unless usage_tier2 == SKIP
      @usage_tier3 = usage_tier3 unless usage_tier3 == SKIP
      @usage_tier4 = usage_tier4 unless usage_tier4 == SKIP
      @total_base = total_base unless total_base == SKIP
      @total_tier1 = total_tier1 unless total_tier1 == SKIP
      @total_tier2 = total_tier2 unless total_tier2 == SKIP
      @total_tier3 = total_tier3 unless total_tier3 == SKIP
      @total_tier4 = total_tier4 unless total_tier4 == SKIP
      @total_due = total_due unless total_due == SKIP
      @net_due = net_due unless net_due == SKIP
      @uom = uom unless uom == SKIP
      @is_paid = is_paid unless is_paid == SKIP
      @status = status unless status == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      session_fee_id = hash.key?('sessionFeeId') ? hash['sessionFeeId'] : SKIP
      fee_type = hash.key?('feeType') ? hash['feeType'] : SKIP
      currency_code = hash.key?('currencyCode') ? hash['currencyCode'] : SKIP
      pricing_type = hash.key?('pricingType') ? hash['pricingType'] : SKIP
      rate_base = hash.key?('rateBase') ? hash['rateBase'] : SKIP
      rate_tier1 = hash.key?('rateTier1') ? hash['rateTier1'] : SKIP
      rate_tier2 = hash.key?('rateTier2') ? hash['rateTier2'] : SKIP
      rate_tier3 = hash.key?('rateTier3') ? hash['rateTier3'] : SKIP
      rate_tier4 = hash.key?('rateTier4') ? hash['rateTier4'] : SKIP
      usage_base = hash.key?('usageBase') ? hash['usageBase'] : SKIP
      usage_tier1 = hash.key?('usageTier1') ? hash['usageTier1'] : SKIP
      usage_tier2 = hash.key?('usageTier2') ? hash['usageTier2'] : SKIP
      usage_tier3 = hash.key?('usageTier3') ? hash['usageTier3'] : SKIP
      usage_tier4 = hash.key?('usageTier4') ? hash['usageTier4'] : SKIP
      total_base = hash.key?('totalBase') ? hash['totalBase'] : SKIP
      total_tier1 = hash.key?('totalTier1') ? hash['totalTier1'] : SKIP
      total_tier2 = hash.key?('totalTier2') ? hash['totalTier2'] : SKIP
      total_tier3 = hash.key?('totalTier3') ? hash['totalTier3'] : SKIP
      total_tier4 = hash.key?('totalTier4') ? hash['totalTier4'] : SKIP
      total_due = hash.key?('totalDue') ? hash['totalDue'] : SKIP
      net_due = hash.key?('netDue') ? hash['netDue'] : SKIP
      uom = hash.key?('uom') ? hash['uom'] : SKIP
      is_paid = hash.key?('isPaid') ? hash['isPaid'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChargingFee.new(session_fee_id: session_fee_id,
                      fee_type: fee_type,
                      currency_code: currency_code,
                      pricing_type: pricing_type,
                      rate_base: rate_base,
                      rate_tier1: rate_tier1,
                      rate_tier2: rate_tier2,
                      rate_tier3: rate_tier3,
                      rate_tier4: rate_tier4,
                      usage_base: usage_base,
                      usage_tier1: usage_tier1,
                      usage_tier2: usage_tier2,
                      usage_tier3: usage_tier3,
                      usage_tier4: usage_tier4,
                      total_base: total_base,
                      total_tier1: total_tier1,
                      total_tier2: total_tier2,
                      total_tier3: total_tier3,
                      total_tier4: total_tier4,
                      total_due: total_due,
                      net_due: net_due,
                      uom: uom,
                      is_paid: is_paid,
                      status: status,
                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} session_fee_id: #{@session_fee_id}, fee_type: #{@fee_type}, currency_code:"\
      " #{@currency_code}, pricing_type: #{@pricing_type}, rate_base: #{@rate_base}, rate_tier1:"\
      " #{@rate_tier1}, rate_tier2: #{@rate_tier2}, rate_tier3: #{@rate_tier3}, rate_tier4:"\
      " #{@rate_tier4}, usage_base: #{@usage_base}, usage_tier1: #{@usage_tier1}, usage_tier2:"\
      " #{@usage_tier2}, usage_tier3: #{@usage_tier3}, usage_tier4: #{@usage_tier4}, total_base:"\
      " #{@total_base}, total_tier1: #{@total_tier1}, total_tier2: #{@total_tier2}, total_tier3:"\
      " #{@total_tier3}, total_tier4: #{@total_tier4}, total_due: #{@total_due}, net_due:"\
      " #{@net_due}, uom: #{@uom}, is_paid: #{@is_paid}, status: #{@status},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} session_fee_id: #{@session_fee_id.inspect}, fee_type: #{@fee_type.inspect},"\
      " currency_code: #{@currency_code.inspect}, pricing_type: #{@pricing_type.inspect},"\
      " rate_base: #{@rate_base.inspect}, rate_tier1: #{@rate_tier1.inspect}, rate_tier2:"\
      " #{@rate_tier2.inspect}, rate_tier3: #{@rate_tier3.inspect}, rate_tier4:"\
      " #{@rate_tier4.inspect}, usage_base: #{@usage_base.inspect}, usage_tier1:"\
      " #{@usage_tier1.inspect}, usage_tier2: #{@usage_tier2.inspect}, usage_tier3:"\
      " #{@usage_tier3.inspect}, usage_tier4: #{@usage_tier4.inspect}, total_base:"\
      " #{@total_base.inspect}, total_tier1: #{@total_tier1.inspect}, total_tier2:"\
      " #{@total_tier2.inspect}, total_tier3: #{@total_tier3.inspect}, total_tier4:"\
      " #{@total_tier4.inspect}, total_due: #{@total_due.inspect}, net_due: #{@net_due.inspect},"\
      " uom: #{@uom.inspect}, is_paid: #{@is_paid.inspect}, status: #{@status.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
