# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module TeslaFleetManagementApi
  # ChargingHistoryItem Model.
  class ChargingHistoryItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :session_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :vin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :site_location_name

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :charge_start_date_time

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :charge_stop_date_time

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :unlatch_date_time

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country_code

    # TODO: Write general description for this method
    # @return [Array[ChargingFee]]
    attr_accessor :fees

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :billing_type

    # TODO: Write general description for this method
    # @return [Array[ChargingInvoice]]
    attr_accessor :invoices

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :vehicle_make_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['session_id'] = 'sessionId'
      @_hash['vin'] = 'vin'
      @_hash['site_location_name'] = 'siteLocationName'
      @_hash['charge_start_date_time'] = 'chargeStartDateTime'
      @_hash['charge_stop_date_time'] = 'chargeStopDateTime'
      @_hash['unlatch_date_time'] = 'unlatchDateTime'
      @_hash['country_code'] = 'countryCode'
      @_hash['fees'] = 'fees'
      @_hash['billing_type'] = 'billingType'
      @_hash['invoices'] = 'invoices'
      @_hash['vehicle_make_type'] = 'vehicleMakeType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        site_location_name
        charge_start_date_time
        charge_stop_date_time
        unlatch_date_time
        country_code
        fees
        billing_type
        invoices
        vehicle_make_type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(session_id:, vin:, site_location_name: SKIP,
                   charge_start_date_time: SKIP, charge_stop_date_time: SKIP,
                   unlatch_date_time: SKIP, country_code: SKIP, fees: SKIP,
                   billing_type: SKIP, invoices: SKIP, vehicle_make_type: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @session_id = session_id
      @vin = vin
      @site_location_name = site_location_name unless site_location_name == SKIP
      @charge_start_date_time = charge_start_date_time unless charge_start_date_time == SKIP
      @charge_stop_date_time = charge_stop_date_time unless charge_stop_date_time == SKIP
      @unlatch_date_time = unlatch_date_time unless unlatch_date_time == SKIP
      @country_code = country_code unless country_code == SKIP
      @fees = fees unless fees == SKIP
      @billing_type = billing_type unless billing_type == SKIP
      @invoices = invoices unless invoices == SKIP
      @vehicle_make_type = vehicle_make_type unless vehicle_make_type == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      session_id = hash.key?('sessionId') ? hash['sessionId'] : nil
      vin = hash.key?('vin') ? hash['vin'] : nil
      site_location_name =
        hash.key?('siteLocationName') ? hash['siteLocationName'] : SKIP
      charge_start_date_time = if hash.key?('chargeStartDateTime')
                                 (DateTimeHelper.from_rfc3339(hash['chargeStartDateTime']) if hash['chargeStartDateTime'])
                               else
                                 SKIP
                               end
      charge_stop_date_time = if hash.key?('chargeStopDateTime')
                                (DateTimeHelper.from_rfc3339(hash['chargeStopDateTime']) if hash['chargeStopDateTime'])
                              else
                                SKIP
                              end
      unlatch_date_time = if hash.key?('unlatchDateTime')
                            (DateTimeHelper.from_rfc3339(hash['unlatchDateTime']) if hash['unlatchDateTime'])
                          else
                            SKIP
                          end
      country_code = hash.key?('countryCode') ? hash['countryCode'] : SKIP
      # Parameter is an array, so we need to iterate through it
      fees = nil
      unless hash['fees'].nil?
        fees = []
        hash['fees'].each do |structure|
          fees << (ChargingFee.from_hash(structure) if structure)
        end
      end

      fees = SKIP unless hash.key?('fees')
      billing_type = hash.key?('billingType') ? hash['billingType'] : SKIP
      # Parameter is an array, so we need to iterate through it
      invoices = nil
      unless hash['invoices'].nil?
        invoices = []
        hash['invoices'].each do |structure|
          invoices << (ChargingInvoice.from_hash(structure) if structure)
        end
      end

      invoices = SKIP unless hash.key?('invoices')
      vehicle_make_type =
        hash.key?('vehicleMakeType') ? hash['vehicleMakeType'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChargingHistoryItem.new(session_id: session_id,
                              vin: vin,
                              site_location_name: site_location_name,
                              charge_start_date_time: charge_start_date_time,
                              charge_stop_date_time: charge_stop_date_time,
                              unlatch_date_time: unlatch_date_time,
                              country_code: country_code,
                              fees: fees,
                              billing_type: billing_type,
                              invoices: invoices,
                              vehicle_make_type: vehicle_make_type,
                              additional_properties: additional_properties)
    end

    def to_custom_charge_start_date_time
      DateTimeHelper.to_rfc3339(charge_start_date_time)
    end

    def to_custom_charge_stop_date_time
      DateTimeHelper.to_rfc3339(charge_stop_date_time)
    end

    def to_custom_unlatch_date_time
      DateTimeHelper.to_rfc3339(unlatch_date_time)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} session_id: #{@session_id}, vin: #{@vin}, site_location_name:"\
      " #{@site_location_name}, charge_start_date_time: #{@charge_start_date_time},"\
      " charge_stop_date_time: #{@charge_stop_date_time}, unlatch_date_time:"\
      " #{@unlatch_date_time}, country_code: #{@country_code}, fees: #{@fees}, billing_type:"\
      " #{@billing_type}, invoices: #{@invoices}, vehicle_make_type: #{@vehicle_make_type},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} session_id: #{@session_id.inspect}, vin: #{@vin.inspect},"\
      " site_location_name: #{@site_location_name.inspect}, charge_start_date_time:"\
      " #{@charge_start_date_time.inspect}, charge_stop_date_time:"\
      " #{@charge_stop_date_time.inspect}, unlatch_date_time: #{@unlatch_date_time.inspect},"\
      " country_code: #{@country_code.inspect}, fees: #{@fees.inspect}, billing_type:"\
      " #{@billing_type.inspect}, invoices: #{@invoices.inspect}, vehicle_make_type:"\
      " #{@vehicle_make_type.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
