# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ChargingLocation Model.
  class ChargingLocation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :distance_miles

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :amenities

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :available_stalls

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total_stalls

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :site_closed

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :billing_info

    # TODO: Write general description for this method
    # @return [Location1]
    attr_accessor :location

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['type'] = 'type'
      @_hash['distance_miles'] = 'distance_miles'
      @_hash['amenities'] = 'amenities'
      @_hash['available_stalls'] = 'available_stalls'
      @_hash['total_stalls'] = 'total_stalls'
      @_hash['site_closed'] = 'site_closed'
      @_hash['billing_info'] = 'billing_info'
      @_hash['location'] = 'location'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        type
        distance_miles
        amenities
        available_stalls
        total_stalls
        site_closed
        billing_info
        location
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name: SKIP, type: SKIP, distance_miles: SKIP,
                   amenities: SKIP, available_stalls: SKIP, total_stalls: SKIP,
                   site_closed: SKIP, billing_info: SKIP, location: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @name = name unless name == SKIP
      @type = type unless type == SKIP
      @distance_miles = distance_miles unless distance_miles == SKIP
      @amenities = amenities unless amenities == SKIP
      @available_stalls = available_stalls unless available_stalls == SKIP
      @total_stalls = total_stalls unless total_stalls == SKIP
      @site_closed = site_closed unless site_closed == SKIP
      @billing_info = billing_info unless billing_info == SKIP
      @location = location unless location == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      distance_miles =
        hash.key?('distance_miles') ? hash['distance_miles'] : SKIP
      amenities = hash.key?('amenities') ? hash['amenities'] : SKIP
      available_stalls =
        hash.key?('available_stalls') ? hash['available_stalls'] : SKIP
      total_stalls = hash.key?('total_stalls') ? hash['total_stalls'] : SKIP
      site_closed = hash.key?('site_closed') ? hash['site_closed'] : SKIP
      billing_info = hash.key?('billing_info') ? hash['billing_info'] : SKIP
      location = Location1.from_hash(hash['location']) if hash['location']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChargingLocation.new(name: name,
                           type: type,
                           distance_miles: distance_miles,
                           amenities: amenities,
                           available_stalls: available_stalls,
                           total_stalls: total_stalls,
                           site_closed: site_closed,
                           billing_info: billing_info,
                           location: location,
                           additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name}, type: #{@type}, distance_miles: #{@distance_miles},"\
      " amenities: #{@amenities}, available_stalls: #{@available_stalls}, total_stalls:"\
      " #{@total_stalls}, site_closed: #{@site_closed}, billing_info: #{@billing_info}, location:"\
      " #{@location}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name.inspect}, type: #{@type.inspect}, distance_miles:"\
      " #{@distance_miles.inspect}, amenities: #{@amenities.inspect}, available_stalls:"\
      " #{@available_stalls.inspect}, total_stalls: #{@total_stalls.inspect}, site_closed:"\
      " #{@site_closed.inspect}, billing_info: #{@billing_info.inspect}, location:"\
      " #{@location.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
