# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ChargingInvoice Model.
  class ChargingInvoice < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :file_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :content_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :invoice_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['file_name'] = 'fileName'
      @_hash['content_id'] = 'contentId'
      @_hash['invoice_type'] = 'invoiceType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        file_name
        content_id
        invoice_type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(file_name: SKIP, content_id: SKIP, invoice_type: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @file_name = file_name unless file_name == SKIP
      @content_id = content_id unless content_id == SKIP
      @invoice_type = invoice_type unless invoice_type == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      file_name = hash.key?('fileName') ? hash['fileName'] : SKIP
      content_id = hash.key?('contentId') ? hash['contentId'] : SKIP
      invoice_type = hash.key?('invoiceType') ? hash['invoiceType'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChargingInvoice.new(file_name: file_name,
                          content_id: content_id,
                          invoice_type: invoice_type,
                          additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} file_name: #{@file_name}, content_id: #{@content_id}, invoice_type:"\
      " #{@invoice_type}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} file_name: #{@file_name.inspect}, content_id: #{@content_id.inspect},"\
      " invoice_type: #{@invoice_type.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
