# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ChargingPeriod Model.
  class ChargingPeriod < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :start_date_time

    # TODO: Write general description for this method
    # @return [Array[ChargingDimension]]
    attr_accessor :dimensions

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['start_date_time'] = 'start_date_time'
      @_hash['dimensions'] = 'dimensions'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        start_date_time
        dimensions
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(start_date_time: SKIP, dimensions: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @start_date_time = start_date_time unless start_date_time == SKIP
      @dimensions = dimensions unless dimensions == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      start_date_time =
        hash.key?('start_date_time') ? hash['start_date_time'] : SKIP
      # Parameter is an array, so we need to iterate through it
      dimensions = nil
      unless hash['dimensions'].nil?
        dimensions = []
        hash['dimensions'].each do |structure|
          dimensions << (ChargingDimension.from_hash(structure) if structure)
        end
      end

      dimensions = SKIP unless hash.key?('dimensions')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChargingPeriod.new(start_date_time: start_date_time,
                         dimensions: dimensions,
                         additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} start_date_time: #{@start_date_time}, dimensions: #{@dimensions},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} start_date_time: #{@start_date_time.inspect}, dimensions:"\
      " #{@dimensions.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
