# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ChargingSessionsData Model.
  class ChargingSessionsData < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[ChargingSession]]
    attr_accessor :data

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :status_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status_message

    # TODO: Write general description for this method
    # @return [Hash[String, String]]
    attr_accessor :timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['data'] = 'data'
      @_hash['status_code'] = 'status_code'
      @_hash['status_message'] = 'status_message'
      @_hash['timestamp'] = 'timestamp'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        data
        status_code
        status_message
        timestamp
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(data: SKIP, status_code: SKIP, status_message: SKIP,
                   timestamp: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @data = data unless data == SKIP
      @status_code = status_code unless status_code == SKIP
      @status_message = status_message unless status_message == SKIP
      @timestamp = timestamp unless timestamp == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      data = nil
      unless hash['data'].nil?
        data = []
        hash['data'].each do |structure|
          data << (ChargingSession.from_hash(structure) if structure)
        end
      end

      data = SKIP unless hash.key?('data')
      status_code = hash.key?('status_code') ? hash['status_code'] : SKIP
      status_message =
        hash.key?('status_message') ? hash['status_message'] : SKIP
      timestamp = hash.key?('timestamp') ? hash['timestamp'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChargingSessionsData.new(data: data,
                               status_code: status_code,
                               status_message: status_message,
                               timestamp: timestamp,
                               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} data: #{@data}, status_code: #{@status_code}, status_message:"\
      " #{@status_message}, timestamp: #{@timestamp}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} data: #{@data.inspect}, status_code: #{@status_code.inspect},"\
      " status_message: #{@status_message.inspect}, timestamp: #{@timestamp.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
