# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ChargeHistory Model.
  class ChargeHistory < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [ChargeStartTime]
    attr_accessor :charge_start_time

    # TODO: Write general description for this method
    # @return [ChargeDuration]
    attr_accessor :charge_duration

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :energy_added_wh

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['charge_start_time'] = 'charge_start_time'
      @_hash['charge_duration'] = 'charge_duration'
      @_hash['energy_added_wh'] = 'energy_added_wh'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(charge_start_time:, charge_duration:, energy_added_wh:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @charge_start_time = charge_start_time
      @charge_duration = charge_duration
      @energy_added_wh = energy_added_wh
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      charge_start_time = ChargeStartTime.from_hash(hash['charge_start_time']) if
        hash['charge_start_time']
      charge_duration = ChargeDuration.from_hash(hash['charge_duration']) if
        hash['charge_duration']
      energy_added_wh =
        hash.key?('energy_added_wh') ? hash['energy_added_wh'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChargeHistory.new(charge_start_time: charge_start_time,
                        charge_duration: charge_duration,
                        energy_added_wh: energy_added_wh,
                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} charge_start_time: #{@charge_start_time}, charge_duration:"\
      " #{@charge_duration}, energy_added_wh: #{@energy_added_wh}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} charge_start_time: #{@charge_start_time.inspect}, charge_duration:"\
      " #{@charge_duration.inspect}, energy_added_wh: #{@energy_added_wh.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
