# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # DefaultRealMode.
  class DefaultRealMode
    DEFAULT_REAL_MODE = [
      # TODO: Write general description for AUTONOMOUS
      AUTONOMOUS = 'autonomous'.freeze,

      # TODO: Write general description for SELF_CONSUMPTION
      SELF_CONSUMPTION = 'self_consumption'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = AUTONOMOUS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'autonomous' then AUTONOMOUS
      when 'self_consumption' then SELF_CONSUMPTION
      else
        default_value
      end
    end
  end
end
