# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # Driver Model.
  class Driver < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :my_tesla_unique_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :user_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :user_id_s

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :vault_uuid

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :driver_first_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :driver_last_name

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :granular_access

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :active_pubkeys

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :public_key

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['my_tesla_unique_id'] = 'my_tesla_unique_id'
      @_hash['user_id'] = 'user_id'
      @_hash['user_id_s'] = 'user_id_s'
      @_hash['vault_uuid'] = 'vault_uuid'
      @_hash['driver_first_name'] = 'driver_first_name'
      @_hash['driver_last_name'] = 'driver_last_name'
      @_hash['granular_access'] = 'granular_access'
      @_hash['active_pubkeys'] = 'active_pubkeys'
      @_hash['public_key'] = 'public_key'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        my_tesla_unique_id
        user_id
        user_id_s
        vault_uuid
        driver_first_name
        driver_last_name
        granular_access
        active_pubkeys
        public_key
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(my_tesla_unique_id: SKIP, user_id: SKIP, user_id_s: SKIP,
                   vault_uuid: SKIP, driver_first_name: SKIP,
                   driver_last_name: SKIP, granular_access: SKIP,
                   active_pubkeys: SKIP, public_key: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @my_tesla_unique_id = my_tesla_unique_id unless my_tesla_unique_id == SKIP
      @user_id = user_id unless user_id == SKIP
      @user_id_s = user_id_s unless user_id_s == SKIP
      @vault_uuid = vault_uuid unless vault_uuid == SKIP
      @driver_first_name = driver_first_name unless driver_first_name == SKIP
      @driver_last_name = driver_last_name unless driver_last_name == SKIP
      @granular_access = granular_access unless granular_access == SKIP
      @active_pubkeys = active_pubkeys unless active_pubkeys == SKIP
      @public_key = public_key unless public_key == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      my_tesla_unique_id =
        hash.key?('my_tesla_unique_id') ? hash['my_tesla_unique_id'] : SKIP
      user_id = hash.key?('user_id') ? hash['user_id'] : SKIP
      user_id_s = hash.key?('user_id_s') ? hash['user_id_s'] : SKIP
      vault_uuid = hash.key?('vault_uuid') ? hash['vault_uuid'] : SKIP
      driver_first_name =
        hash.key?('driver_first_name') ? hash['driver_first_name'] : SKIP
      driver_last_name =
        hash.key?('driver_last_name') ? hash['driver_last_name'] : SKIP
      granular_access =
        hash.key?('granular_access') ? hash['granular_access'] : SKIP
      active_pubkeys =
        hash.key?('active_pubkeys') ? hash['active_pubkeys'] : SKIP
      public_key = hash.key?('public_key') ? hash['public_key'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Driver.new(my_tesla_unique_id: my_tesla_unique_id,
                 user_id: user_id,
                 user_id_s: user_id_s,
                 vault_uuid: vault_uuid,
                 driver_first_name: driver_first_name,
                 driver_last_name: driver_last_name,
                 granular_access: granular_access,
                 active_pubkeys: active_pubkeys,
                 public_key: public_key,
                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} my_tesla_unique_id: #{@my_tesla_unique_id}, user_id: #{@user_id},"\
      " user_id_s: #{@user_id_s}, vault_uuid: #{@vault_uuid}, driver_first_name:"\
      " #{@driver_first_name}, driver_last_name: #{@driver_last_name}, granular_access:"\
      " #{@granular_access}, active_pubkeys: #{@active_pubkeys}, public_key: #{@public_key},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} my_tesla_unique_id: #{@my_tesla_unique_id.inspect}, user_id:"\
      " #{@user_id.inspect}, user_id_s: #{@user_id_s.inspect}, vault_uuid: #{@vault_uuid.inspect},"\
      " driver_first_name: #{@driver_first_name.inspect}, driver_last_name:"\
      " #{@driver_last_name.inspect}, granular_access: #{@granular_access.inspect},"\
      " active_pubkeys: #{@active_pubkeys.inspect}, public_key: #{@public_key.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
