# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # EnterprisePayerRequest Model.
  class EnterprisePayerRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :role

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :federation_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['role'] = 'role'
      @_hash['federation_id'] = 'federation_id'
      @_hash['account_id'] = 'account_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        federation_id
        account_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(role:, federation_id: SKIP, account_id: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @role = role
      @federation_id = federation_id unless federation_id == SKIP
      @account_id = account_id unless account_id == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      role = hash.key?('role') ? hash['role'] : nil
      federation_id = hash.key?('federation_id') ? hash['federation_id'] : SKIP
      account_id = hash.key?('account_id') ? hash['account_id'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      EnterprisePayerRequest.new(role: role,
                                 federation_id: federation_id,
                                 account_id: account_id,
                                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} role: #{@role}, federation_id: #{@federation_id}, account_id:"\
      " #{@account_id}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} role: #{@role.inspect}, federation_id: #{@federation_id.inspect},"\
      " account_id: #{@account_id.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
