# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # FleetTelemetryJwsRequest Model.
  class FleetTelemetryJwsRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :token

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :vins

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash['vins'] = 'vins'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        token
        vins
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(token: SKIP, vins: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @token = token unless token == SKIP
      @vins = vins unless vins == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = hash.key?('token') ? hash['token'] : SKIP
      vins = hash.key?('vins') ? hash['vins'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      FleetTelemetryJwsRequest.new(token: token,
                                   vins: vins,
                                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token}, vins: #{@vins}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token.inspect}, vins: #{@vins.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
