# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # kind_getWallConnectorChargingHistory.
  class KindGetWallConnectorChargingHistory
    KIND_GET_WALL_CONNECTOR_CHARGING_HISTORY = [
      # TODO: Write general description for CHARGE
      CHARGE = 'charge'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = CHARGE)
      return default_value if value.nil?

      default_value
    end
  end
end
