# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # kind.
  class Kind
    KIND = [
      # TODO: Write general description for BACKUP
      BACKUP = 'backup'.freeze,

      # TODO: Write general description for ENERGY
      ENERGY = 'energy'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = BACKUP)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'backup' then BACKUP
      when 'energy' then ENERGY
      else
        default_value
      end
    end
  end
end
