# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # Location Model.
  class Location < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['country'] = 'country'
      @_hash['name'] = 'name'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        country
        name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(country: SKIP, name: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @country = country unless country == SKIP
      @name = name unless name == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      country = hash.key?('country') ? hash['country'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Location.new(country: country,
                   name: name,
                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} country: #{@country}, name: #{@name}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} country: #{@country.inspect}, name: #{@name.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
