# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # OAuth 2 scopes supported by the API
  class OAuthScopeOauth2
    O_AUTH_SCOPE_OAUTH2 = [
      # Allow Tesla customers to sign in to the application with their Tesla
      # credentials.
      OPENID = 'openid'.freeze,

      # Allow getting a refresh token without needing user to log in again.
      OFFLINE_ACCESS = 'offline_access'.freeze,

      # Contact information, home address, profile picture, and referral
      # information.
      USER_DATA = 'user_data'.freeze,

      # Allow access to your vehicle’s live data, service history, service
      # scheduling data, service communications, eligible upgrades, nearby
      # Superchargers and ownership details.
      VEHICLE_DEVICE_DATA = 'vehicle_device_data'.freeze,

      # Allow access to vehicle location information, including precise and
      # coarse location data.
      VEHICLE_LOCATION = 'vehicle_location'.freeze,

      # Commands like add/remove driver, access Live Camera, unlock, wake up,
      # remote start, and schedule software updates.
      VEHICLE_CMDS = 'vehicle_cmds'.freeze,

      # Vehicle charging history, billed amount, charging location, and commands
      # to schedule, start, or stop charging.
      VEHICLE_CHARGING_CMDS = 'vehicle_charging_cmds'.freeze,

      # Access detailed vehicle specifications. Partner tokens only; usable
      # without owner authorization.
      VEHICLE_SPECS = 'vehicle_specs'.freeze,

      # Energy live status, site info, backup history, energy history, and
      # charge history.
      ENERGY_DEVICE_DATA = 'energy_device_data'.freeze,

      # Update energy settings like backup reserve percent, operation mode, and
      # storm mode.
      ENERGY_CMDS = 'energy_cmds'.freeze,

      # Allow access to enterprise management functions for businesses.
      ENTERPRISE_MANAGEMENT = 'enterprise_management'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      O_AUTH_SCOPE_OAUTH2.include?(value)
    end

    def self.from_value(value, default_value = OPENID)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'openid' then OPENID
      when 'offline_access' then OFFLINE_ACCESS
      when 'user_data' then USER_DATA
      when 'vehicle_device_data' then VEHICLE_DEVICE_DATA
      when 'vehicle_location' then VEHICLE_LOCATION
      when 'vehicle_cmds' then VEHICLE_CMDS
      when 'vehicle_charging_cmds' then VEHICLE_CHARGING_CMDS
      when 'vehicle_specs' then VEHICLE_SPECS
      when 'energy_device_data' then ENERGY_DEVICE_DATA
      when 'energy_cmds' then ENERGY_CMDS
      when 'enterprise_management' then ENTERPRISE_MANAGEMENT
      else
        default_value
      end
    end
  end
end
