# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # OffGridVehicleChargingReserveRequest Model.
  class OffGridVehicleChargingReserveRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :off_grid_vehicle_charging_reserve_percent

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['off_grid_vehicle_charging_reserve_percent'] =
        'off_grid_vehicle_charging_reserve_percent'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(off_grid_vehicle_charging_reserve_percent:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @off_grid_vehicle_charging_reserve_percent = off_grid_vehicle_charging_reserve_percent
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      off_grid_vehicle_charging_reserve_percent =
        hash.key?('off_grid_vehicle_charging_reserve_percent') ? hash['off_grid_vehicle_charging_reserve_percent'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      OffGridVehicleChargingReserveRequest.new(off_grid_vehicle_charging_reserve_percent: off_grid_vehicle_charging_reserve_percent,
                                               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} off_grid_vehicle_charging_reserve_percent:"\
      " #{@off_grid_vehicle_charging_reserve_percent}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} off_grid_vehicle_charging_reserve_percent:"\
      " #{@off_grid_vehicle_charging_reserve_percent.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
