# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # Pagination Model.
  class Pagination < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :previous

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :mnext

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :current

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :per_page

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :pages

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['previous'] = 'previous'
      @_hash['mnext'] = 'next'
      @_hash['current'] = 'current'
      @_hash['per_page'] = 'per_page'
      @_hash['count'] = 'count'
      @_hash['pages'] = 'pages'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        previous
        mnext
        current
        per_page
        count
        pages
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        previous
        mnext
      ]
    end

    def initialize(previous: SKIP, mnext: SKIP, current: SKIP, per_page: SKIP,
                   count: SKIP, pages: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @previous = previous unless previous == SKIP
      @mnext = mnext unless mnext == SKIP
      @current = current unless current == SKIP
      @per_page = per_page unless per_page == SKIP
      @count = count unless count == SKIP
      @pages = pages unless pages == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      previous = hash.key?('previous') ? hash['previous'] : SKIP
      mnext = hash.key?('next') ? hash['next'] : SKIP
      current = hash.key?('current') ? hash['current'] : SKIP
      per_page = hash.key?('per_page') ? hash['per_page'] : SKIP
      count = hash.key?('count') ? hash['count'] : SKIP
      pages = hash.key?('pages') ? hash['pages'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Pagination.new(previous: previous,
                     mnext: mnext,
                     current: current,
                     per_page: per_page,
                     count: count,
                     pages: pages,
                     additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} previous: #{@previous}, mnext: #{@mnext}, current: #{@current}, per_page:"\
      " #{@per_page}, count: #{@count}, pages: #{@pages}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} previous: #{@previous.inspect}, mnext: #{@mnext.inspect}, current:"\
      " #{@current.inspect}, per_page: #{@per_page.inspect}, count: #{@count.inspect}, pages:"\
      " #{@pages.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
