# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # PriceComponent Model.
  class PriceComponent < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :price

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :step_size

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['price'] = 'price'
      @_hash['step_size'] = 'step_size'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        price
        step_size
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type: SKIP, price: SKIP, step_size: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @type = type unless type == SKIP
      @price = price unless price == SKIP
      @step_size = step_size unless step_size == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : SKIP
      price = hash.key?('price') ? hash['price'] : SKIP
      step_size = hash.key?('step_size') ? hash['step_size'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PriceComponent.new(type: type,
                         price: price,
                         step_size: step_size,
                         additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, price: #{@price}, step_size: #{@step_size},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, price: #{@price.inspect}, step_size:"\
      " #{@step_size.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
