# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ResponseOrdersResponse Model.
  class ResponseOrdersResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :vehicle_map_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :reference_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :vin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :order_status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :order_substatus

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :model_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :locale

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mkt_options

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_b2b

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['vehicle_map_id'] = 'vehicleMapId'
      @_hash['reference_number'] = 'referenceNumber'
      @_hash['vin'] = 'vin'
      @_hash['order_status'] = 'orderStatus'
      @_hash['order_substatus'] = 'orderSubstatus'
      @_hash['model_code'] = 'modelCode'
      @_hash['country_code'] = 'countryCode'
      @_hash['locale'] = 'locale'
      @_hash['mkt_options'] = 'mktOptions'
      @_hash['is_b2b'] = 'isB2b'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(vehicle_map_id:, reference_number:, vin:, order_status:,
                   order_substatus:, model_code:, country_code:, locale:,
                   mkt_options:, is_b2b:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @vehicle_map_id = vehicle_map_id
      @reference_number = reference_number
      @vin = vin
      @order_status = order_status
      @order_substatus = order_substatus
      @model_code = model_code
      @country_code = country_code
      @locale = locale
      @mkt_options = mkt_options
      @is_b2b = is_b2b
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      vehicle_map_id = hash.key?('vehicleMapId') ? hash['vehicleMapId'] : nil
      reference_number =
        hash.key?('referenceNumber') ? hash['referenceNumber'] : nil
      vin = hash.key?('vin') ? hash['vin'] : nil
      order_status = hash.key?('orderStatus') ? hash['orderStatus'] : nil
      order_substatus =
        hash.key?('orderSubstatus') ? hash['orderSubstatus'] : nil
      model_code = hash.key?('modelCode') ? hash['modelCode'] : nil
      country_code = hash.key?('countryCode') ? hash['countryCode'] : nil
      locale = hash.key?('locale') ? hash['locale'] : nil
      mkt_options = hash.key?('mktOptions') ? hash['mktOptions'] : nil
      is_b2b = hash.key?('isB2b') ? hash['isB2b'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ResponseOrdersResponse.new(vehicle_map_id: vehicle_map_id,
                                 reference_number: reference_number,
                                 vin: vin,
                                 order_status: order_status,
                                 order_substatus: order_substatus,
                                 model_code: model_code,
                                 country_code: country_code,
                                 locale: locale,
                                 mkt_options: mkt_options,
                                 is_b2b: is_b2b,
                                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} vehicle_map_id: #{@vehicle_map_id}, reference_number: #{@reference_number},"\
      " vin: #{@vin}, order_status: #{@order_status}, order_substatus: #{@order_substatus},"\
      " model_code: #{@model_code}, country_code: #{@country_code}, locale: #{@locale},"\
      " mkt_options: #{@mkt_options}, is_b2b: #{@is_b2b}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} vehicle_map_id: #{@vehicle_map_id.inspect}, reference_number:"\
      " #{@reference_number.inspect}, vin: #{@vin.inspect}, order_status:"\
      " #{@order_status.inspect}, order_substatus: #{@order_substatus.inspect}, model_code:"\
      " #{@model_code.inspect}, country_code: #{@country_code.inspect}, locale:"\
      " #{@locale.inspect}, mkt_options: #{@mkt_options.inspect}, is_b2b: #{@is_b2b.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
