# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ResponseRegionResponse Model.
  class ResponseRegionResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :region

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :fleet_api_base_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['region'] = 'region'
      @_hash['fleet_api_base_url'] = 'fleet_api_base_url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(region:, fleet_api_base_url:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @region = region
      @fleet_api_base_url = fleet_api_base_url
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      region = hash.key?('region') ? hash['region'] : nil
      fleet_api_base_url =
        hash.key?('fleet_api_base_url') ? hash['fleet_api_base_url'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ResponseRegionResponse.new(region: region,
                                 fleet_api_base_url: fleet_api_base_url,
                                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} region: #{@region}, fleet_api_base_url: #{@fleet_api_base_url},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} region: #{@region.inspect}, fleet_api_base_url:"\
      " #{@fleet_api_base_url.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
