# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ResponseApi1DxWarrantyDetailsResponse Model.
  class ResponseApi1DxWarrantyDetailsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[WarrantyItem]]
    attr_accessor :active_warranty

    # TODO: Write general description for this method
    # @return [Array[WarrantyItem]]
    attr_accessor :upcoming_warranty

    # TODO: Write general description for this method
    # @return [Array[WarrantyItem]]
    attr_accessor :expired_warranty

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['active_warranty'] = 'activeWarranty'
      @_hash['upcoming_warranty'] = 'upcomingWarranty'
      @_hash['expired_warranty'] = 'expiredWarranty'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        active_warranty
        upcoming_warranty
        expired_warranty
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(active_warranty: SKIP, upcoming_warranty: SKIP,
                   expired_warranty: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @active_warranty = active_warranty unless active_warranty == SKIP
      @upcoming_warranty = upcoming_warranty unless upcoming_warranty == SKIP
      @expired_warranty = expired_warranty unless expired_warranty == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      active_warranty = nil
      unless hash['activeWarranty'].nil?
        active_warranty = []
        hash['activeWarranty'].each do |structure|
          active_warranty << (WarrantyItem.from_hash(structure) if structure)
        end
      end

      active_warranty = SKIP unless hash.key?('activeWarranty')
      # Parameter is an array, so we need to iterate through it
      upcoming_warranty = nil
      unless hash['upcomingWarranty'].nil?
        upcoming_warranty = []
        hash['upcomingWarranty'].each do |structure|
          upcoming_warranty << (WarrantyItem.from_hash(structure) if structure)
        end
      end

      upcoming_warranty = SKIP unless hash.key?('upcomingWarranty')
      # Parameter is an array, so we need to iterate through it
      expired_warranty = nil
      unless hash['expiredWarranty'].nil?
        expired_warranty = []
        hash['expiredWarranty'].each do |structure|
          expired_warranty << (WarrantyItem.from_hash(structure) if structure)
        end
      end

      expired_warranty = SKIP unless hash.key?('expiredWarranty')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ResponseApi1DxWarrantyDetailsResponse.new(active_warranty: active_warranty,
                                                upcoming_warranty: upcoming_warranty,
                                                expired_warranty: expired_warranty,
                                                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} active_warranty: #{@active_warranty}, upcoming_warranty:"\
      " #{@upcoming_warranty}, expired_warranty: #{@expired_warranty}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} active_warranty: #{@active_warranty.inspect}, upcoming_warranty:"\
      " #{@upcoming_warranty.inspect}, expired_warranty: #{@expired_warranty.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
