# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ResponseCalendarHistoryResponse Model.
  class ResponseCalendarHistoryResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[Event]]
    attr_accessor :events

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total_events

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['events'] = 'events'
      @_hash['total_events'] = 'total_events'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(events:, total_events:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @events = events
      @total_events = total_events
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      events = nil
      unless hash['events'].nil?
        events = []
        hash['events'].each do |structure|
          events << (Event.from_hash(structure) if structure)
        end
      end

      events = nil unless hash.key?('events')
      total_events = hash.key?('total_events') ? hash['total_events'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ResponseCalendarHistoryResponse.new(events: events,
                                          total_events: total_events,
                                          additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} events: #{@events}, total_events: #{@total_events}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} events: #{@events.inspect}, total_events: #{@total_events.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
