# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module TeslaFleetManagementApi
  # ResponseRegisterPartnerResponse Model.
  class ResponseRegisterPartnerResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :client_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :domain

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :ca

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :created_at

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :updated_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :enterprise_tier

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :issuer

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :csr

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :csr_updated_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :public_key

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :public_key_hash

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['client_id'] = 'client_id'
      @_hash['name'] = 'name'
      @_hash['description'] = 'description'
      @_hash['domain'] = 'domain'
      @_hash['ca'] = 'ca'
      @_hash['created_at'] = 'created_at'
      @_hash['updated_at'] = 'updated_at'
      @_hash['enterprise_tier'] = 'enterprise_tier'
      @_hash['account_id'] = 'account_id'
      @_hash['issuer'] = 'issuer'
      @_hash['csr'] = 'csr'
      @_hash['csr_updated_at'] = 'csr_updated_at'
      @_hash['public_key'] = 'public_key'
      @_hash['public_key_hash'] = 'public_key_hash'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        description
        ca
        issuer
        csr
        csr_updated_at
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        ca
        issuer
        csr
        csr_updated_at
      ]
    end

    def initialize(client_id:, name:, domain:, created_at:, updated_at:,
                   enterprise_tier:, account_id:, public_key:, public_key_hash:,
                   description: SKIP, ca: SKIP, issuer: SKIP, csr: SKIP,
                   csr_updated_at: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @client_id = client_id
      @name = name
      @description = description unless description == SKIP
      @domain = domain
      @ca = ca unless ca == SKIP
      @created_at = created_at
      @updated_at = updated_at
      @enterprise_tier = enterprise_tier
      @account_id = account_id
      @issuer = issuer unless issuer == SKIP
      @csr = csr unless csr == SKIP
      @csr_updated_at = csr_updated_at unless csr_updated_at == SKIP
      @public_key = public_key
      @public_key_hash = public_key_hash
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      client_id = hash.key?('client_id') ? hash['client_id'] : nil
      name = hash.key?('name') ? hash['name'] : nil
      domain = hash.key?('domain') ? hash['domain'] : nil
      created_at = if hash.key?('created_at')
                     (DateTimeHelper.from_rfc3339(hash['created_at']) if hash['created_at'])
                   end
      updated_at = if hash.key?('updated_at')
                     (DateTimeHelper.from_rfc3339(hash['updated_at']) if hash['updated_at'])
                   end
      enterprise_tier =
        hash.key?('enterprise_tier') ? hash['enterprise_tier'] : nil
      account_id = hash.key?('account_id') ? hash['account_id'] : nil
      public_key = hash.key?('public_key') ? hash['public_key'] : nil
      public_key_hash =
        hash.key?('public_key_hash') ? hash['public_key_hash'] : nil
      description = hash.key?('description') ? hash['description'] : SKIP
      ca = hash.key?('ca') ? hash['ca'] : SKIP
      issuer = hash.key?('issuer') ? hash['issuer'] : SKIP
      csr = hash.key?('csr') ? hash['csr'] : SKIP
      csr_updated_at = if hash.key?('csr_updated_at')
                         (DateTimeHelper.from_rfc3339(hash['csr_updated_at']) if hash['csr_updated_at'])
                       else
                         SKIP
                       end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ResponseRegisterPartnerResponse.new(client_id: client_id,
                                          name: name,
                                          domain: domain,
                                          created_at: created_at,
                                          updated_at: updated_at,
                                          enterprise_tier: enterprise_tier,
                                          account_id: account_id,
                                          public_key: public_key,
                                          public_key_hash: public_key_hash,
                                          description: description,
                                          ca: ca,
                                          issuer: issuer,
                                          csr: csr,
                                          csr_updated_at: csr_updated_at,
                                          additional_properties: additional_properties)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    def to_custom_updated_at
      DateTimeHelper.to_rfc3339(updated_at)
    end

    def to_custom_csr_updated_at
      DateTimeHelper.to_rfc3339(csr_updated_at)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} client_id: #{@client_id}, name: #{@name}, description: #{@description},"\
      " domain: #{@domain}, ca: #{@ca}, created_at: #{@created_at}, updated_at: #{@updated_at},"\
      " enterprise_tier: #{@enterprise_tier}, account_id: #{@account_id}, issuer: #{@issuer}, csr:"\
      " #{@csr}, csr_updated_at: #{@csr_updated_at}, public_key: #{@public_key}, public_key_hash:"\
      " #{@public_key_hash}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} client_id: #{@client_id.inspect}, name: #{@name.inspect}, description:"\
      " #{@description.inspect}, domain: #{@domain.inspect}, ca: #{@ca.inspect}, created_at:"\
      " #{@created_at.inspect}, updated_at: #{@updated_at.inspect}, enterprise_tier:"\
      " #{@enterprise_tier.inspect}, account_id: #{@account_id.inspect}, issuer:"\
      " #{@issuer.inspect}, csr: #{@csr.inspect}, csr_updated_at: #{@csr_updated_at.inspect},"\
      " public_key: #{@public_key.inspect}, public_key_hash: #{@public_key_hash.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
