# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # Response3 Model.
  class Response3 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[ChargingLocation]]
    attr_accessor :destination_charging

    # TODO: Write general description for this method
    # @return [Array[ChargingLocation]]
    attr_accessor :superchargers

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['destination_charging'] = 'destination_charging'
      @_hash['superchargers'] = 'superchargers'
      @_hash['timestamp'] = 'timestamp'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        destination_charging
        superchargers
        timestamp
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(destination_charging: SKIP, superchargers: SKIP,
                   timestamp: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @destination_charging = destination_charging unless destination_charging == SKIP
      @superchargers = superchargers unless superchargers == SKIP
      @timestamp = timestamp unless timestamp == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      destination_charging = nil
      unless hash['destination_charging'].nil?
        destination_charging = []
        hash['destination_charging'].each do |structure|
          destination_charging << (ChargingLocation.from_hash(structure) if structure)
        end
      end

      destination_charging = SKIP unless hash.key?('destination_charging')
      # Parameter is an array, so we need to iterate through it
      superchargers = nil
      unless hash['superchargers'].nil?
        superchargers = []
        hash['superchargers'].each do |structure|
          superchargers << (ChargingLocation.from_hash(structure) if structure)
        end
      end

      superchargers = SKIP unless hash.key?('superchargers')
      timestamp = hash.key?('timestamp') ? hash['timestamp'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Response3.new(destination_charging: destination_charging,
                    superchargers: superchargers,
                    timestamp: timestamp,
                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} destination_charging: #{@destination_charging}, superchargers:"\
      " #{@superchargers}, timestamp: #{@timestamp}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} destination_charging: #{@destination_charging.inspect}, superchargers:"\
      " #{@superchargers.inspect}, timestamp: #{@timestamp.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
