# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module TeslaFleetManagementApi
  # ResponseLiveStatusResponse Model.
  class ResponseLiveStatusResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :solar_power

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :energy_left

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_pack_energy

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :percentage_charged

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :backup_capable

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :battery_power

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :load_power

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :grid_status

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :grid_power

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :island_status

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :storm_mode_active

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['solar_power'] = 'solar_power'
      @_hash['energy_left'] = 'energy_left'
      @_hash['total_pack_energy'] = 'total_pack_energy'
      @_hash['percentage_charged'] = 'percentage_charged'
      @_hash['backup_capable'] = 'backup_capable'
      @_hash['battery_power'] = 'battery_power'
      @_hash['load_power'] = 'load_power'
      @_hash['grid_status'] = 'grid_status'
      @_hash['grid_power'] = 'grid_power'
      @_hash['island_status'] = 'island_status'
      @_hash['storm_mode_active'] = 'storm_mode_active'
      @_hash['timestamp'] = 'timestamp'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        battery_power
        load_power
        grid_status
        grid_power
        island_status
        storm_mode_active
        timestamp
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(solar_power:, energy_left:, total_pack_energy:,
                   percentage_charged:, backup_capable:, battery_power: SKIP,
                   load_power: SKIP, grid_status: SKIP, grid_power: SKIP,
                   island_status: SKIP, storm_mode_active: SKIP,
                   timestamp: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @solar_power = solar_power
      @energy_left = energy_left
      @total_pack_energy = total_pack_energy
      @percentage_charged = percentage_charged
      @backup_capable = backup_capable
      @battery_power = battery_power unless battery_power == SKIP
      @load_power = load_power unless load_power == SKIP
      @grid_status = grid_status unless grid_status == SKIP
      @grid_power = grid_power unless grid_power == SKIP
      @island_status = island_status unless island_status == SKIP
      @storm_mode_active = storm_mode_active unless storm_mode_active == SKIP
      @timestamp = timestamp unless timestamp == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      solar_power = hash.key?('solar_power') ? hash['solar_power'] : nil
      energy_left = hash.key?('energy_left') ? hash['energy_left'] : nil
      total_pack_energy =
        hash.key?('total_pack_energy') ? hash['total_pack_energy'] : nil
      percentage_charged =
        hash.key?('percentage_charged') ? hash['percentage_charged'] : nil
      backup_capable =
        hash.key?('backup_capable') ? hash['backup_capable'] : nil
      battery_power = hash.key?('battery_power') ? hash['battery_power'] : SKIP
      load_power = hash.key?('load_power') ? hash['load_power'] : SKIP
      grid_status = hash.key?('grid_status') ? hash['grid_status'] : SKIP
      grid_power = hash.key?('grid_power') ? hash['grid_power'] : SKIP
      island_status = hash.key?('island_status') ? hash['island_status'] : SKIP
      storm_mode_active =
        hash.key?('storm_mode_active') ? hash['storm_mode_active'] : SKIP
      timestamp = if hash.key?('timestamp')
                    (DateTimeHelper.from_rfc3339(hash['timestamp']) if hash['timestamp'])
                  else
                    SKIP
                  end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ResponseLiveStatusResponse.new(solar_power: solar_power,
                                     energy_left: energy_left,
                                     total_pack_energy: total_pack_energy,
                                     percentage_charged: percentage_charged,
                                     backup_capable: backup_capable,
                                     battery_power: battery_power,
                                     load_power: load_power,
                                     grid_status: grid_status,
                                     grid_power: grid_power,
                                     island_status: island_status,
                                     storm_mode_active: storm_mode_active,
                                     timestamp: timestamp,
                                     additional_properties: additional_properties)
    end

    def to_custom_timestamp
      DateTimeHelper.to_rfc3339(timestamp)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} solar_power: #{@solar_power}, energy_left: #{@energy_left},"\
      " total_pack_energy: #{@total_pack_energy}, percentage_charged: #{@percentage_charged},"\
      " backup_capable: #{@backup_capable}, battery_power: #{@battery_power}, load_power:"\
      " #{@load_power}, grid_status: #{@grid_status}, grid_power: #{@grid_power}, island_status:"\
      " #{@island_status}, storm_mode_active: #{@storm_mode_active}, timestamp: #{@timestamp},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} solar_power: #{@solar_power.inspect}, energy_left: #{@energy_left.inspect},"\
      " total_pack_energy: #{@total_pack_energy.inspect}, percentage_charged:"\
      " #{@percentage_charged.inspect}, backup_capable: #{@backup_capable.inspect}, battery_power:"\
      " #{@battery_power.inspect}, load_power: #{@load_power.inspect}, grid_status:"\
      " #{@grid_status.inspect}, grid_power: #{@grid_power.inspect}, island_status:"\
      " #{@island_status.inspect}, storm_mode_active: #{@storm_mode_active.inspect}, timestamp:"\
      " #{@timestamp.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
