# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ResponseMeResponse Model.
  class ResponseMeResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :email

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :full_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :profile_image_url

    # TODO: Write general description for this method
    # @return [UUID | String]
    attr_accessor :vault_uuid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['email'] = 'email'
      @_hash['full_name'] = 'full_name'
      @_hash['profile_image_url'] = 'profile_image_url'
      @_hash['vault_uuid'] = 'vault_uuid'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(email:, full_name:, profile_image_url:, vault_uuid:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @email = email
      @full_name = full_name
      @profile_image_url = profile_image_url
      @vault_uuid = vault_uuid
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      email = hash.key?('email') ? hash['email'] : nil
      full_name = hash.key?('full_name') ? hash['full_name'] : nil
      profile_image_url =
        hash.key?('profile_image_url') ? hash['profile_image_url'] : nil
      vault_uuid = hash.key?('vault_uuid') ? hash['vault_uuid'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ResponseMeResponse.new(email: email,
                             full_name: full_name,
                             profile_image_url: profile_image_url,
                             vault_uuid: vault_uuid,
                             additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} email: #{@email}, full_name: #{@full_name}, profile_image_url:"\
      " #{@profile_image_url}, vault_uuid: #{@vault_uuid}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} email: #{@email.inspect}, full_name: #{@full_name.inspect},"\
      " profile_image_url: #{@profile_image_url.inspect}, vault_uuid: #{@vault_uuid.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
