# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # ResponseApi1DxVehiclesOptionsResponse Model.
  class ResponseApi1DxVehiclesOptionsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[VehicleOption]]
    attr_accessor :codes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['codes'] = 'codes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        codes
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(codes: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @codes = codes unless codes == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      codes = nil
      unless hash['codes'].nil?
        codes = []
        hash['codes'].each do |structure|
          codes << (VehicleOption.from_hash(structure) if structure)
        end
      end

      codes = SKIP unless hash.key?('codes')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ResponseApi1DxVehiclesOptionsResponse.new(codes: codes,
                                                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} codes: #{@codes}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} codes: #{@codes.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
