# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # Signaling Model.
  class Signaling < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :enabled

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :subscribe_connectivity

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :use_auth_token

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['enabled'] = 'enabled'
      @_hash['subscribe_connectivity'] = 'subscribe_connectivity'
      @_hash['use_auth_token'] = 'use_auth_token'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(enabled:, subscribe_connectivity:, use_auth_token:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @enabled = enabled
      @subscribe_connectivity = subscribe_connectivity
      @use_auth_token = use_auth_token
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      enabled = hash.key?('enabled') ? hash['enabled'] : nil
      subscribe_connectivity =
        hash.key?('subscribe_connectivity') ? hash['subscribe_connectivity'] : nil
      use_auth_token =
        hash.key?('use_auth_token') ? hash['use_auth_token'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Signaling.new(enabled: enabled,
                    subscribe_connectivity: subscribe_connectivity,
                    use_auth_token: use_auth_token,
                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} enabled: #{@enabled}, subscribe_connectivity: #{@subscribe_connectivity},"\
      " use_auth_token: #{@use_auth_token}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} enabled: #{@enabled.inspect}, subscribe_connectivity:"\
      " #{@subscribe_connectivity.inspect}, use_auth_token: #{@use_auth_token.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
