# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # TariffElement Model.
  class TariffElement < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[PriceComponent]]
    attr_accessor :price_components

    # TODO: Write general description for this method
    # @return [Hash[String, Object]]
    attr_accessor :restrictions

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['price_components'] = 'price_components'
      @_hash['restrictions'] = 'restrictions'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        price_components
        restrictions
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(price_components: SKIP, restrictions: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @price_components = price_components unless price_components == SKIP
      @restrictions = restrictions unless restrictions == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      price_components = nil
      unless hash['price_components'].nil?
        price_components = []
        hash['price_components'].each do |structure|
          price_components << (PriceComponent.from_hash(structure) if structure)
        end
      end

      price_components = SKIP unless hash.key?('price_components')
      restrictions = hash.key?('restrictions') ? hash['restrictions'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      TariffElement.new(price_components: price_components,
                        restrictions: restrictions,
                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} price_components: #{@price_components}, restrictions: #{@restrictions},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} price_components: #{@price_components.inspect}, restrictions:"\
      " #{@restrictions.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
