# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # Tariffs Model.
  class Tariffs < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :currency

    # TODO: Write general description for this method
    # @return [Array[TariffElement]]
    attr_accessor :elements

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['currency'] = 'currency'
      @_hash['elements'] = 'elements'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        currency
        elements
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(currency: SKIP, elements: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @currency = currency unless currency == SKIP
      @elements = elements unless elements == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      currency = hash.key?('currency') ? hash['currency'] : SKIP
      # Parameter is an array, so we need to iterate through it
      elements = nil
      unless hash['elements'].nil?
        elements = []
        hash['elements'].each do |structure|
          elements << (TariffElement.from_hash(structure) if structure)
        end
      end

      elements = SKIP unless hash.key?('elements')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Tariffs.new(currency: currency,
                  elements: elements,
                  additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} currency: #{@currency}, elements: #{@elements}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} currency: #{@currency.inspect}, elements: #{@elements.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
