# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # TotalCost Model.
  class TotalCost < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :excl_vat

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :incl_vat

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :vat

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['excl_vat'] = 'excl_vat'
      @_hash['incl_vat'] = 'incl_vat'
      @_hash['vat'] = 'vat'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        excl_vat
        incl_vat
        vat
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(excl_vat: SKIP, incl_vat: SKIP, vat: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @excl_vat = excl_vat unless excl_vat == SKIP
      @incl_vat = incl_vat unless incl_vat == SKIP
      @vat = vat unless vat == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      excl_vat = hash.key?('excl_vat') ? hash['excl_vat'] : SKIP
      incl_vat = hash.key?('incl_vat') ? hash['incl_vat'] : SKIP
      vat = hash.key?('vat') ? hash['vat'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      TotalCost.new(excl_vat: excl_vat,
                    incl_vat: incl_vat,
                    vat: vat,
                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} excl_vat: #{@excl_vat}, incl_vat: #{@incl_vat}, vat: #{@vat},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} excl_vat: #{@excl_vat.inspect}, incl_vat: #{@incl_vat.inspect}, vat:"\
      " #{@vat.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
