# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # VehicleBase Model.
  class VehicleBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :vehicle_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :vin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :display_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :access_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :state

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :in_service

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :calendar_enabled

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['vehicle_id'] = 'vehicle_id'
      @_hash['vin'] = 'vin'
      @_hash['display_name'] = 'display_name'
      @_hash['access_type'] = 'access_type'
      @_hash['state'] = 'state'
      @_hash['in_service'] = 'in_service'
      @_hash['calendar_enabled'] = 'calendar_enabled'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        vehicle_id
        vin
        display_name
        access_type
        state
        in_service
        calendar_enabled
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id: SKIP, vehicle_id: SKIP, vin: SKIP, display_name: SKIP,
                   access_type: SKIP, state: SKIP, in_service: SKIP,
                   calendar_enabled: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @id = id unless id == SKIP
      @vehicle_id = vehicle_id unless vehicle_id == SKIP
      @vin = vin unless vin == SKIP
      @display_name = display_name unless display_name == SKIP
      @access_type = access_type unless access_type == SKIP
      @state = state unless state == SKIP
      @in_service = in_service unless in_service == SKIP
      @calendar_enabled = calendar_enabled unless calendar_enabled == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      vehicle_id = hash.key?('vehicle_id') ? hash['vehicle_id'] : SKIP
      vin = hash.key?('vin') ? hash['vin'] : SKIP
      display_name = hash.key?('display_name') ? hash['display_name'] : SKIP
      access_type = hash.key?('access_type') ? hash['access_type'] : SKIP
      state = hash.key?('state') ? hash['state'] : SKIP
      in_service = hash.key?('in_service') ? hash['in_service'] : SKIP
      calendar_enabled =
        hash.key?('calendar_enabled') ? hash['calendar_enabled'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      VehicleBase.new(id: id,
                      vehicle_id: vehicle_id,
                      vin: vin,
                      display_name: display_name,
                      access_type: access_type,
                      state: state,
                      in_service: in_service,
                      calendar_enabled: calendar_enabled,
                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, vehicle_id: #{@vehicle_id}, vin: #{@vin}, display_name:"\
      " #{@display_name}, access_type: #{@access_type}, state: #{@state}, in_service:"\
      " #{@in_service}, calendar_enabled: #{@calendar_enabled}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, vehicle_id: #{@vehicle_id.inspect}, vin:"\
      " #{@vin.inspect}, display_name: #{@display_name.inspect}, access_type:"\
      " #{@access_type.inspect}, state: #{@state.inspect}, in_service: #{@in_service.inspect},"\
      " calendar_enabled: #{@calendar_enabled.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
