# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # VehicleOption Model.
  class VehicleOption < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :display_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :color_code

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_active

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['code'] = 'code'
      @_hash['display_name'] = 'displayName'
      @_hash['color_code'] = 'colorCode'
      @_hash['is_active'] = 'isActive'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        code
        display_name
        color_code
        is_active
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        color_code
      ]
    end

    def initialize(code: SKIP, display_name: SKIP, color_code: SKIP,
                   is_active: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @code = code unless code == SKIP
      @display_name = display_name unless display_name == SKIP
      @color_code = color_code unless color_code == SKIP
      @is_active = is_active unless is_active == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash.key?('code') ? hash['code'] : SKIP
      display_name = hash.key?('displayName') ? hash['displayName'] : SKIP
      color_code = hash.key?('colorCode') ? hash['colorCode'] : SKIP
      is_active = hash.key?('isActive') ? hash['isActive'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      VehicleOption.new(code: code,
                        display_name: display_name,
                        color_code: color_code,
                        is_active: is_active,
                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} code: #{@code}, display_name: #{@display_name}, color_code: #{@color_code},"\
      " is_active: #{@is_active}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} code: #{@code.inspect}, display_name: #{@display_name.inspect}, color_code:"\
      " #{@color_code.inspect}, is_active: #{@is_active.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
