# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module TeslaFleetManagementApi
  # WarrantyItem Model.
  class WarrantyItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :warranty_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :warranty_display_name

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :expiration_date

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :expiration_odometer

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :odometer_unit

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :warranty_expired_on

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :coverage_age_in_years

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['warranty_type'] = 'warrantyType'
      @_hash['warranty_display_name'] = 'warrantyDisplayName'
      @_hash['expiration_date'] = 'expirationDate'
      @_hash['expiration_odometer'] = 'expirationOdometer'
      @_hash['odometer_unit'] = 'odometerUnit'
      @_hash['warranty_expired_on'] = 'warrantyExpiredOn'
      @_hash['coverage_age_in_years'] = 'coverageAgeInYears'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        warranty_type
        warranty_display_name
        expiration_date
        expiration_odometer
        odometer_unit
        warranty_expired_on
        coverage_age_in_years
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        warranty_expired_on
      ]
    end

    def initialize(warranty_type: SKIP, warranty_display_name: SKIP,
                   expiration_date: SKIP, expiration_odometer: SKIP,
                   odometer_unit: SKIP, warranty_expired_on: SKIP,
                   coverage_age_in_years: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @warranty_type = warranty_type unless warranty_type == SKIP
      @warranty_display_name = warranty_display_name unless warranty_display_name == SKIP
      @expiration_date = expiration_date unless expiration_date == SKIP
      @expiration_odometer = expiration_odometer unless expiration_odometer == SKIP
      @odometer_unit = odometer_unit unless odometer_unit == SKIP
      @warranty_expired_on = warranty_expired_on unless warranty_expired_on == SKIP
      @coverage_age_in_years = coverage_age_in_years unless coverage_age_in_years == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      warranty_type = hash.key?('warrantyType') ? hash['warrantyType'] : SKIP
      warranty_display_name =
        hash.key?('warrantyDisplayName') ? hash['warrantyDisplayName'] : SKIP
      expiration_date = if hash.key?('expirationDate')
                          (DateTimeHelper.from_rfc3339(hash['expirationDate']) if hash['expirationDate'])
                        else
                          SKIP
                        end
      expiration_odometer =
        hash.key?('expirationOdometer') ? hash['expirationOdometer'] : SKIP
      odometer_unit = hash.key?('odometerUnit') ? hash['odometerUnit'] : SKIP
      warranty_expired_on =
        hash.key?('warrantyExpiredOn') ? hash['warrantyExpiredOn'] : SKIP
      coverage_age_in_years =
        hash.key?('coverageAgeInYears') ? hash['coverageAgeInYears'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WarrantyItem.new(warranty_type: warranty_type,
                       warranty_display_name: warranty_display_name,
                       expiration_date: expiration_date,
                       expiration_odometer: expiration_odometer,
                       odometer_unit: odometer_unit,
                       warranty_expired_on: warranty_expired_on,
                       coverage_age_in_years: coverage_age_in_years,
                       additional_properties: additional_properties)
    end

    def to_custom_expiration_date
      DateTimeHelper.to_rfc3339(expiration_date)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} warranty_type: #{@warranty_type}, warranty_display_name:"\
      " #{@warranty_display_name}, expiration_date: #{@expiration_date}, expiration_odometer:"\
      " #{@expiration_odometer}, odometer_unit: #{@odometer_unit}, warranty_expired_on:"\
      " #{@warranty_expired_on}, coverage_age_in_years: #{@coverage_age_in_years},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} warranty_type: #{@warranty_type.inspect}, warranty_display_name:"\
      " #{@warranty_display_name.inspect}, expiration_date: #{@expiration_date.inspect},"\
      " expiration_odometer: #{@expiration_odometer.inspect}, odometer_unit:"\
      " #{@odometer_unit.inspect}, warranty_expired_on: #{@warranty_expired_on.inspect},"\
      " coverage_age_in_years: #{@coverage_age_in_years.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
