# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # WhichTrunk.
  class WhichTrunk
    WHICH_TRUNK = [
      # TODO: Write general description for FRONT
      FRONT = 'front'.freeze,

      # TODO: Write general description for REAR
      REAR = 'rear'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = FRONT)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'front' then FRONT
      when 'rear' then REAR
      else
        default_value
      end
    end
  end
end
