# tesla_fleet_management_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module TeslaFleetManagementApi
  # Utility class for OAuth 2 authorization and token management.
  class Oauth2 < CoreLibrary::HeaderAuth
    include CoreLibrary
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'Oauth2: OAuthToken is undefined or expired.'
    end

    # Initialization constructor.
    def initialize(oauth_2_credentials, config)
      auth_params = {}
      @_oauth_client_id = oauth_2_credentials.oauth_client_id unless
        oauth_2_credentials.nil? || oauth_2_credentials.oauth_client_id.nil?
      @_oauth_client_secret = oauth_2_credentials.oauth_client_secret unless
        oauth_2_credentials.nil? || oauth_2_credentials.oauth_client_secret.nil?
      @_oauth_redirect_uri = oauth_2_credentials.oauth_redirect_uri unless
        oauth_2_credentials.nil? || oauth_2_credentials.oauth_redirect_uri.nil?
      @_oauth_token = oauth_2_credentials.oauth_token unless
        oauth_2_credentials.nil? || oauth_2_credentials.oauth_token.nil?
      @_config = config
      @_o_auth_api = OauthAuthorizationController.new(config)
      auth_params[:Authorization] = "Bearer #{@_oauth_token.access_token}" unless @_oauth_token.nil?

      super auth_params
    end

    # Validates the oAuth token.
    # @return [Boolean] true if the token is present and not expired.
    def valid
      !@_oauth_token.nil? && !token_expired?(@_oauth_token)
    end

    # Builds and returns an authorization URL.
    # The user is expected to obtain an authorization code from this URL and then call the
    # fetch token function with that authorization code.
    # @param [String] state An opaque state string.
    # @param [Hash] additional_params Any additional query parameters to be added to the URL.
    # @return [String] The authorization URL.
    def get_authorization_url(state: nil, additional_params: nil)
      auth_url = @_config.get_base_uri_executor.call(Server::AUTH_SERVER)
      auth_url += '/authorize'
      query_params = {
        'response_type' => 'code',
        'client_id' => @_oauth_client_id,
        'redirect_uri' => @_oauth_redirect_uri
      }
      query_params['scope'] = Array(@_o_auth_scopes).compact.join(' ') if @_o_auth_scopes
      query_params['state'] = state if state
      query_params.merge!(additional_params) if additional_params
      auth_url = APIHelper.append_url_with_query_parameters(auth_url,
                                                            query_params)
      APIHelper.clean_url(auth_url)
    end

    # Builds the basic auth header for endpoints in the OAuth Authorization Controller.
    # @return [String] The value of the Authentication header.
    def build_basic_auth_header
      "Basic #{AuthHelper.get_base64_encoded_value(@_oauth_client_id, @_oauth_client_secret)}"
    end

    # Fetches the token.
    # @param [String] auth_code The authentication code.
    # @param [Hash] additional_params Any additional form parameters.
    # @return [OAuthToken] The oAuth token instance.
    def fetch_token(auth_code, additional_params: nil)
      token = @_o_auth_api.request_token_oauth_2(
        build_basic_auth_header,
        auth_code,
        @_oauth_redirect_uri,
        _field_parameters: additional_params
      ).data
      if token.respond_to?('expires_in') && !token.expires_in.nil?
        token.expiry = AuthHelper.get_token_expiry(token.expires_in, Time.now.utc.to_i)
      end
      token
    end

    # Checks if OAuth token has expired.
    # @param [OAuthToken] token The oAuth token instance.
    # @return [Boolean] true if the token is present and not expired.
    def token_expired?(token)
      token.respond_to?('expiry') && AuthHelper.token_expired?(token.expiry)
    end

    # Refreshes OAuth token.
    # @param [Hash] additional_params Any additional form parameters.
    # @return [OAuthToken] The oAuth token instance.
    def refresh_token(additional_params: nil)
      token = @_o_auth_api.refresh_token_oauth_2(
        build_basic_auth_header,
        @_oauth_token.refresh_token,
        _field_parameters: additional_params
      ).data
      if token.respond_to?('expires_in') && !token.expires_in.nil?
        token.expiry = AuthHelper.get_token_expiry(token.expires_in, Time.now.utc.to_i)
      end
      token
    end
  end

  # Data class for Oauth2Credentials.
  class Oauth2Credentials
    attr_reader :oauth_client_id, :oauth_client_secret, :oauth_redirect_uri,
                :oauth_token

    def initialize(oauth_client_id:, oauth_client_secret:, oauth_redirect_uri:,
                   oauth_token: nil)
      raise ArgumentError, 'oauth_client_id cannot be nil' if oauth_client_id.nil?
      raise ArgumentError, 'oauth_client_secret cannot be nil' if oauth_client_secret.nil?
      raise ArgumentError, 'oauth_redirect_uri cannot be nil' if oauth_redirect_uri.nil?

      @oauth_client_id = oauth_client_id
      @oauth_client_secret = oauth_client_secret
      @oauth_redirect_uri = oauth_redirect_uri
      @oauth_token = oauth_token
    end

    def self.from_env
      oauth_client_id = ENV['OAUTH_2_OAUTH_CLIENT_ID']
      oauth_client_secret = ENV['OAUTH_2_OAUTH_CLIENT_SECRET']
      oauth_redirect_uri = ENV['OAUTH_2_OAUTH_REDIRECT_URI']
      all_nil = [
        oauth_client_id,
        oauth_client_secret,
        oauth_redirect_uri
      ].all?(&:nil?)
      return nil if all_nil

      new(oauth_client_id: oauth_client_id,
          oauth_client_secret: oauth_client_secret,
          oauth_redirect_uri: oauth_redirect_uri)
    end

    def clone_with(oauth_client_id: nil, oauth_client_secret: nil,
                   oauth_redirect_uri: nil, oauth_token: nil)
      oauth_client_id ||= self.oauth_client_id
      oauth_client_secret ||= self.oauth_client_secret
      oauth_redirect_uri ||= self.oauth_redirect_uri
      oauth_token ||= self.oauth_token

      Oauth2Credentials.new(oauth_client_id: oauth_client_id,
                            oauth_client_secret: oauth_client_secret,
                            oauth_redirect_uri: oauth_redirect_uri,
                            oauth_token: oauth_token)
    end
  end
end
